name: Build and release pdf

on: push

jobs:
  build:
    name: Build and release pdf
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile LateX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
